// This file used to be auto-generated by Lovable. We've taken it over —
// the prior version called `createClient(undefined, undefined, ...)` when
// env vars were missing at build time, which threw at module-eval and
// gave end-users a blank white screen with no clue what was wrong.
//
// Now: we validate the three required vars and, if any are missing,
// expose a flag the ErrorBoundary checks so we can show a real message.
import { createClient, type SupabaseClient } from "@supabase/supabase-js";
import type { Database } from "./types";

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL as string | undefined;
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY as string | undefined;
const SUPABASE_PROJECT_ID = import.meta.env.VITE_SUPABASE_PROJECT_ID as string | undefined;

export const MISSING_SUPABASE_ENV: string[] = [
  !SUPABASE_URL && "VITE_SUPABASE_URL",
  !SUPABASE_PUBLISHABLE_KEY && "VITE_SUPABASE_PUBLISHABLE_KEY",
  !SUPABASE_PROJECT_ID && "VITE_SUPABASE_PROJECT_ID",
].filter(Boolean) as string[];

export const isSupabaseConfigured = MISSING_SUPABASE_ENV.length === 0;

// If config is missing, log it loudly so it shows up in the browser
// console for the engineer debugging — but don't throw, so the rest of
// the app can render an error screen instead of going blank.
if (!isSupabaseConfigured && typeof window !== "undefined") {
  // eslint-disable-next-line no-console
  console.error(
    "[Wetzels] Supabase is not configured. Missing env vars:",
    MISSING_SUPABASE_ENV.join(", "),
    "\nCheck your deployment's environment-variable settings.",
  );
}

// We still export a `supabase` symbol so existing imports keep working.
// When config is missing we hand back a stub that rejects every call with
// a clear message instead of a confusing TypeError. Real callers should
// have been blocked by the ErrorBoundary before they get this far.
function makeStub(): SupabaseClient<Database> {
  const err = () =>
    Promise.reject(
      new Error(
        `Supabase client is not configured. Missing env vars: ${MISSING_SUPABASE_ENV.join(", ")}`,
      ),
    );
  const handler: ProxyHandler<object> = {
    get(_t, prop) {
      if (prop === "then") return undefined; // never let this look like a thenable
      return new Proxy(err, handler);
    },
    apply: err,
  };
  return new Proxy(function () {} as unknown as object, handler) as unknown as SupabaseClient<Database>;
}

export const supabase: SupabaseClient<Database> = isSupabaseConfigured
  ? createClient<Database>(SUPABASE_URL!, SUPABASE_PUBLISHABLE_KEY!, {
      auth: {
        storage: localStorage,
        persistSession: true,
        autoRefreshToken: true,
      },
    })
  : makeStub();

// Convenience: callers that build function URLs no longer need to
// reach for `import.meta.env` directly. Single source of truth.
export const SUPABASE_FUNCTIONS_BASE = SUPABASE_PROJECT_ID
  ? `https://${SUPABASE_PROJECT_ID}.supabase.co/functions/v1`
  : "";
